sonar.projectKey=YOUR_GITHUB_USERNAME_grade-management-system
sonar.organization=YOUR_GITHUB_USERNAME

sonar.projectName=Student Grade Management System
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.python.version=3.8

sonar.tests=tests/
sonar.test.inclusions=tests/**/*.py
